export const SYSTEM_ORDER_VERSION = 'v2-order.1';

export const SYSTEM_ORDER = [
  'VALIDATE_AND_ORDER_ACTIONS',
  'RESOLVE_FOUNDER_ACTION',
  'PROGRESS_MANUAL_AND_AGENT_WORK',
  'ROUTE_COHORTS',
  'RESOLVE_CUSTOMERS_AND_COLLECTIONS',
  'RESOLVE_OPERATIONS_AND_ROT',
  'RESOLVE_FINANCE',
  'DERIVE_PRESSURE_FAILURES_AND_ALERTS',
  'CLOSE_QUARTER_OR_RUN',
  'EMIT_EVENTS_LEDGER_AND_HASH',
] as const;
