import {describe,it,expect} from 'vitest';
import {advance,arr,command,createCompany,monthlyCost,priceCursor,priceTarget,pricingQuote,pressure,rebaseCompany,replayCompany,validateCompany} from '../../src/game/founder/engine';
import {initialBoard,measureOperationsTickets,mergeOrder,operationsTicketPrice,operationsTicketSupply,productBrief} from '../../src/game/founder/toys';
import {P,skillRank} from '../../src/game/founder/profile';
import {checksum,decodeSave,encodeSave} from '../../src/game/founder/save';
import type {Company} from '../../src/game/founder/model';
const start=(seed=77)=>command(createCompany(seed),{type:'start'});
function legacySave(s:Company,version:'founder-candidate.2'|'founder-candidate.3'){
 const legacy=structuredClone(s) as unknown as Record<string,unknown>;legacy.version=version;legacy.status='running';legacy.paused=false;legacy.actions=s.actions.map(({tick,command})=>({tick,command}));
 for(const key of ['contractVersion','contentVersion','actionCursor','actionResults','phase','resumePhase','pendingDraftQuarter','inventory','jobs'])delete legacy[key];
 const data=JSON.stringify(legacy);return JSON.stringify({version:1,data,checksum:checksum(data)});
}
function accountFixture(seed=77){const s=start(seed);s.tick=1300;s.focus='expansion';s.accounts=[{id:800,origin:800,segment:0,count:1,price:4000,basePrice:4000,fit:.8,health:80,defects:0,born:0,caredUntil:0,addons:0,threat:0,earned:0,remainder:0,active:true}];return s;}
function retentionFixture(seed=77){const s=accountFixture();s.seed=seed;s.focus='retention';s.accounts[0].threat=s.tick+100;s.accounts[0].problem={id:801,kind:'reliability',label:'Workflow failed mid-run',detail:'A real customer workflow stopped.',openedAt:s.tick,deadline:s.tick+100,severity:2,workRequired:8,workCompleted:0,exposedArr:arr(s)};return s;}
function combine(s:Company){for(let guard=0;guard<30;guard++){const board=s.package.board??initialBoard();let pair:number[]=[];for(let i=0;i<16;i++)for(let j=i+1;j<16;j++)if(board[i]&&board[j]&&board[i]!.family===board[j]!.family&&board[i]!.tier===board[j]!.tier&&board[i]!.tier<3+s.accounts[0].addons)pair=[i,j];if(!pair.length)break;s=command(s,{type:'merge',account:800,from:pair[0],to:pair[1],expectedTier:board[pair[0]]!.tier});}return s;}
describe('tactile founder state and accounting',()=>{
 it('restores an out-of-order recipe and ships only after the remaining slots are filled and tested',()=>{
  let s=start();s.focus='product';s.leads=[{id:4,segment:2,count:1,expires:600,fit:.9}];
  const parts=productBrief(s,s.leads[0]).parts,last=parts.length-1;
  s=command(s,{type:'part',job:4,slot:last,part:parts[last]});
  const cash=s.cash;
  s=decodeSave(encodeSave(s));
  expect(s.recipe.slots.slice(0,last)).toEqual(Array(last).fill(null));
  expect(s.recipe.slots[last]).toBe(parts[last]);expect(s.cash).toBe(cash);
  s=command(s,{type:'test-build',job:4});expect(s.recipe.tested).toBe(false);
  s=command(s,{type:'ship',job:4,early:false});expect(s.trials).toHaveLength(0);
  for(let slot=0;slot<last;slot++)s=command(s,{type:'part',job:4,slot,part:parts[slot]});
  s=command(s,{type:'test-build',job:4});expect(s.recipe.tested).toBe(true);
  s=command(s,{type:'ship',job:4,early:false});expect(s.trials).toHaveLength(1);expect(s.leads).toHaveLength(0);
 });
 it('charges a sampled ticket once, persists inspection without settlement, claims selectively, and abandons the price',()=>{
  let s=command(start(920),{type:'focus',work:'operations'});s.cash=1_000_000;s.strain=4;for(const f of Object.keys(s.rot) as (keyof typeof s.rot)[])s.rot[f]=.4;s=rebaseCompany(s);
  const opening=s.cash,price=operationsTicketPrice(0);s=command(s,{type:'ops-deal'});expect(s.cash).toBe(opening-price);expect(s.ops.status).toBe('bought');expect(s.ops.patches).toHaveLength(4);const sampled=structuredClone(s.ops.patches);
  const duplicate=command(s,{type:'ops-deal'});expect(duplicate.cash).toBe(s.cash);expect(duplicate.ops.id).toBe(s.ops.id);expect(duplicate.actionResults.at(-1)?.reason).toBe('invalid-command');
  s=decodeSave(encodeSave(s));expect(s.ops.patches).toEqual(sampled);const positive=s.ops.patches.find(p=>p.sentiment==='positive')!,before={cash:s.cash,strain:s.strain,rot:structuredClone(s.rot),incidents:structuredClone(s.incidents)};
  s=command(s,{type:'ops-inspect',card:s.ops.id,cell:positive.id});expect({cash:s.cash,strain:s.strain,rot:s.rot,incidents:s.incidents}).toEqual(before);expect(s.actionResults.at(-1)?.operations).toMatchObject({operation:'inspected',valueDelta:0});
  s=command(s,{type:'ops-claim',card:s.ops.id,cell:positive.id});expect(s.ops.claimed).toEqual([positive.id]);expect(s.ops.claimedBy[positive.id]).toBe('manual');expect(s.actionResults.at(-1)?.operations).toMatchObject({operation:'claimed',patchIds:[positive.id],valueDelta:positive.valueCents});
  const settled=structuredClone(s);s=command(s,{type:'ops-claim',card:s.ops.id,cell:positive.id});expect(s.ops).toEqual(settled.ops);expect(s.actionResults.at(-1)?.reason).toBe('stale-job');
  s=command(s,{type:'ops-discard',card:s.ops.id});expect(s.ops).toMatchObject({active:false,status:'closed',closedReason:'abandoned'});expect(s.cash).toBeGreaterThanOrEqual(opening-price);const closed=structuredClone(s);s=command(s,{type:'ops-claim',card:s.ops.id,cell:positive.id});expect(s.ops).toEqual(closed.ops);expect(replayCompany(s)).toEqual(s);validateCompany(s);
 });
 it('routes generic job cancellation through the same paid-ticket abandonment boundary',()=>{
  let s=command(start(9201),{type:'focus',work:'operations'});s.cash=1_000_000;s=rebaseCompany(s);const opening=s.cash,price=operationsTicketPrice(0);s=command(s,{type:'ops-deal'});const ticket=s.ops.id;
  expect(s.jobs.reservations.some(r=>r.jobId===`operations:${ticket}`)).toBe(true);s=command(s,{type:'cancel-job',job:`operations:${ticket}`});
  expect(s.cash).toBe(opening-price);expect(s.ops).toMatchObject({id:ticket,active:false,status:'closed',closedReason:'abandoned'});expect(s.operationsResolution).toMatchObject({operation:'abandoned',status:'closed'});expect(s.jobs.closed[`operations:${ticket}`]?.reason).toBe('cancelled');expect(s.jobs.reservations.some(r=>r.jobId===`operations:${ticket}`)).toBe(false);
  const cancelled=structuredClone(s);s=command(s,{type:'cancel-job',job:`operations:${ticket}`});expect(s.ops).toEqual(cancelled.ops);expect(s.actionResults.at(-1)?.reason).toBe('cancelled-job');expect(decodeSave(encodeSave(s))).toEqual(s);expect(replayCompany(s)).toEqual(s);validateCompany(s);
 });
 it('hands a partially claimed ticket to automation, resolves every remainder, and never repays the founder patch',()=>{
  let s=command(start(921),{type:'focus',work:'operations'});s.cash=1_000_000;s.ranks.operations={craft:2,scale:2,automate:4,luck:2};s.deployed.operations=0;s.risky.operations=true;s=rebaseCompany(s);s=advance(s,20);expect(s.ops.id).toBe(0);s=command(s,{type:'ops-deal'});const ticket=s.ops.id,firstPositive=s.ops.patches.find(p=>p.sentiment==='positive')!;
  s=command(s,{type:'ops-inspect',card:ticket,cell:firstPositive.id});s=command(s,{type:'ops-claim',card:ticket,cell:firstPositive.id});const founderValue=s.operationsReturns.manual.patchValue;s=command(s,{type:'focus',work:'demand'});s=advance(s,4);
  expect(s.ops).toMatchObject({id:ticket,active:false,status:'closed',closedReason:'resolved'});expect(s.ops.claimed).toHaveLength(s.ops.patches.length);expect(s.ops.claimedBy[firstPositive.id]).toBe('manual');expect(Object.values(s.ops.claimedBy)).toContain('automated');expect(s.operationsReturns.manual.patchValue).toBe(founderValue);expect(s.operationsReturns.automated.upkeep).toBeGreaterThan(0);expect(replayCompany(s)).toEqual(s);expect(decodeSave(encodeSave(s))).toEqual(s);
 });
 it('uses finite quarterly supply and resets only in a new quarter',()=>{
  let s=command(start(922),{type:'focus',work:'operations'});s.cash=1_000_000;const supply=operationsTicketSupply(0);
  for(let n=0;n<supply;n++){s=command(s,{type:'ops-deal'});expect(s.ops.active).toBe(true);s=command(s,{type:'ops-discard',card:s.ops.id});s=advance(s,P.functions.operations.manual_seconds*10);}
  const cash=s.cash,id=s.ops.id;s=command(s,{type:'ops-deal'});expect(s.ops.id).toBe(id);expect(s.cash).toBe(cash);expect(s.actionResults.at(-1)?.reason).toBe('invalid-command');s.quarter++;s=command(s,{type:'ops-deal'});expect(s.ops.active).toBe(true);expect(s.ops.quarter).toBe(s.quarter);expect(s.ops.used).toBe(1);
 });
 it('applies incident costs and keeps an unaffordable negative cash settlement explicit under O02',()=>{
  let incidentSeed=1;for(;;incidentSeed++){const probe=command(command(start(incidentSeed),{type:'focus',work:'operations'}),{type:'ops-deal'});if(probe.ops.patches.some(p=>p.effect.kind==='incident'&&p.effect.mode==='open'))break;}
  let incident=command(start(incidentSeed),{type:'focus',work:'operations'});incident.cash=1_000_000;incident=command(incident,{type:'ops-deal'});const incidentPatch=incident.ops.patches.find(p=>p.effect.kind==='incident'&&p.effect.mode==='open')!;const cost=monthlyCost(incident),load=pressure(incident).load;incident=command(incident,{type:'ops-inspect',card:incident.ops.id,cell:incidentPatch.id});incident=command(incident,{type:'ops-claim',card:incident.ops.id,cell:incidentPatch.id});expect(incident.incidents.filter(i=>i.active)).toHaveLength(1);expect(monthlyCost(incident)).toBeGreaterThan(cost);expect(pressure(incident).load).toBeGreaterThan(load);
  let lossSeed=1;for(;;lossSeed++){const probe=command(command(start(lossSeed),{type:'focus',work:'operations'}),{type:'ops-deal'});if(probe.ops.patches.some(p=>p.effect.kind==='cash'&&p.effect.cents<0))break;}
  let loss=command(start(lossSeed),{type:'focus',work:'operations'});const price=operationsTicketPrice(0);loss.cash=price+1;loss=command(loss,{type:'ops-deal'});const negative=loss.ops.patches.find(p=>p.effect.kind==='cash'&&p.effect.cents<0)!;loss=command(loss,{type:'ops-inspect',card:loss.ops.id,cell:negative.id});loss=command(loss,{type:'ops-claim',card:loss.ops.id,cell:negative.id});expect(loss.phase).toBe('failure');expect(loss.failure).toContain('Operations ticket settlement');expect(loss.ops.claimed).toContain(negative.id);expect(loss.cash).toBe(1);
 });
 it('applies typed strain and rot patches and can close a persisted live incident',()=>{
  let strainSeed=1;for(;;strainSeed++){const probe=command(command(start(strainSeed),{type:'focus',work:'operations'}),{type:'ops-deal'});const patch=probe.ops.patches.find(p=>p.effect.kind==='strain');if(patch?.effect.kind==='strain'&&patch.effect.direction==='add')break;}
  let strain=command(start(strainSeed),{type:'focus',work:'operations'});strain.cash=1_000_000;strain=command(strain,{type:'ops-deal'});const strainPatch=strain.ops.patches.find(p=>p.effect.kind==='strain')!,beforeStrain=strain.strain;strain=command(strain,{type:'ops-inspect',card:strain.ops.id,cell:strainPatch.id});strain=command(strain,{type:'ops-claim',card:strain.ops.id,cell:strainPatch.id});expect(strain.strain).toBeGreaterThan(beforeStrain);
  let rotSeed=1;for(;;rotSeed++){const probe=command(command(start(rotSeed),{type:'focus',work:'operations'}),{type:'ops-deal'});const patch=probe.ops.patches.find(p=>p.effect.kind==='rot');if(patch?.effect.kind==='rot'&&patch.effect.direction==='repair')break;}
  let rot=command(start(rotSeed),{type:'focus',work:'operations'});rot.cash=1_000_000;rot=command(rot,{type:'ops-deal'});const rotPatch=rot.ops.patches.find(p=>p.effect.kind==='rot')!;if(rotPatch.effect.kind!=='rot')throw new Error('Expected rot patch.');rot.rot[rotPatch.effect.target]=.5;rot=command(rot,{type:'ops-inspect',card:rot.ops.id,cell:rotPatch.id});rot=command(rot,{type:'ops-claim',card:rot.ops.id,cell:rotPatch.id});expect(rot.rot[rotPatch.effect.target]).toBeLessThan(.5);
  let closeSeed=1;for(;;closeSeed++){const probe=command(command(start(closeSeed),{type:'focus',work:'operations'}),{type:'ops-deal'});const patch=probe.ops.patches.find(p=>p.effect.kind==='incident');if(patch?.effect.kind==='incident'&&patch.effect.mode==='resolve')break;}
  let close=command(start(closeSeed),{type:'focus',work:'operations'});close.cash=1_000_000;close=command(close,{type:'ops-deal'});const closePatch=close.ops.patches.find(p=>p.effect.kind==='incident')!;if(closePatch.effect.kind!=='incident')throw new Error('Expected incident patch.');close.incidents=[{id:'existing',ticketId:0,patchId:0,target:closePatch.effect.target,label:'Existing live incident',severity:2,openedAt:0,monthlyCostCents:500,active:true}];close=command(close,{type:'ops-inspect',card:close.ops.id,cell:closePatch.id});close=command(close,{type:'ops-claim',card:close.ops.id,cell:closePatch.id});expect(close.incidents[0]).toMatchObject({active:false,resolvedAt:close.tick});expect(close.operationsResolution?.incidentsResolved).toEqual(['existing']);
 });
 it('measures random rank-zero and wider Luck tickets after price and automation upkeep, with all sixteen ranks defined',()=>{
  for(const axis of ['craft','scale','automate','luck'] as const)for(let rank=1;rank<=4;rank++)expect(skillRank('operations',axis,rank)).toMatchObject({id:`operations.${axis}.${rank}`,effectId:`skill:operations.${axis}.${rank}`});
  const base=measureOperationsTickets(20_000,0,0,1),lucky=measureOperationsTickets(20_000,4,4,4);expect(base.automated.variance).toBeGreaterThan(0);expect(lucky.automated.variance).toBeGreaterThan(base.automated.variance);expect(base.manual.meanAfterPrice).toBeGreaterThan(base.automated.meanAfterPrice);expect(base.automated.meanAfterPriceAndUpkeep).toBeGreaterThan(0);expect(lucky.automated.meanAfterPriceAndUpkeep).toBeGreaterThan(0);expect(lucky.automated.lossRate).toBeGreaterThan(0);expect(lucky.automated.minimum).toBeLessThan(0);expect(lucky.automated.maximum).toBeGreaterThan(0);
 });
 it('migrates retired maintenance sheets without resetting financial history',()=>{
  const s=start();s.operationsNet=123;s.ops.active=true;s.cash=98765;const next=decodeSave(legacySave(s,'founder-candidate.3'));expect(next.cash).toBe(98765);expect(next.operationsNet).toBe(123);expect(next.ops).toMatchObject({active:false,status:'offered'});expect(next.operationsReturns.manual.net).toBe(0);expect(next.version).toBe(P.version);expect(replayCompany(next)).toEqual(next);
 });
 it('requires correct recipe tests, invalidates tests on changes, and never ships a stale job',()=>{let s=start();s.focus='product';s.leads=[{id:4,segment:2,count:1,expires:600,fit:.9}];const parts=productBrief(s,s.leads[0]).parts;s=command(s,{type:'part',job:4,slot:0,part:(parts[0]+1)%6});s=command(s,{type:'test-build',job:4});expect(s.recipe.tested).toBe(false);s=command(s,{type:'ship',job:4,early:false});expect(s.trials).toHaveLength(0);parts.forEach((part,slot)=>{s=command(s,{type:'part',job:4,slot,part});});s=command(s,{type:'test-build',job:4});expect(s.recipe.tested).toBe(true);s=command(s,{type:'part',job:4,slot:0,part:parts[0]});expect(s.recipe.tested).toBe(false);s=command(s,{type:'test-build',job:4});s=command(s,{type:'ship',job:4,early:false});expect(s.trials).toHaveLength(1);const count=s.trials.length;s=command(s,{type:'ship',job:4,early:false});expect(s.trials.length).toBe(count);});
 it('persists explicit recipe states and ships one reserved order into a trial without ARR',()=>{let s=start(404);s.focus='product';s.leads=[{id:44,segment:1,count:1,expires:600,fit:.9}];s=rebaseCompany(s);const parts=productBrief(s,s.leads[0]).parts,openingArr=arr(s),openingCash=s.cash;
  s=command(s,{type:'part',job:44,slot:0,part:(parts[0]+1)%6});s=command(s,{type:'test-build',job:44});expect(s.recipe.verification).toBe('incorrect');
  parts.forEach((part,slot)=>{s=command(s,{type:'part',job:44,slot,part});});expect(s.recipe.verification).toBe('incomplete');s=decodeSave(encodeSave(s));expect(s.recipe.verification).toBe('incomplete');
  s=command(s,{type:'test-build',job:44});expect(s.recipe.verification).toBe('verified');s=command(s,{type:'ship',job:44,early:false});expect(s.productResolution).toMatchObject({leadId:44,trialsCreated:1,arrDelta:0,outcome:'shipped'});expect(s.actionResults.at(-1)?.product).toEqual(s.productResolution);expect(s.trials).toHaveLength(1);expect(arr(s)).toBe(openingArr);expect(s.cash).toBe(openingCash-P.functions.product.attempt_cost_cents);const shipped=s.trials.length;s=command(s,{type:'ship',job:44,early:false});expect(s.trials).toHaveLength(shipped);expect(s.actionResults.at(-1)?.reason).toBe('stale-job');expect(replayCompany(s)).toEqual(s);
 });
 it('gives a fresh Product brief a two-minute assembly window',()=>{let s=start();s.channel=0;s.focus='demand';s=command(s,{type:'demand',pursue:true,signal:s.signal});const lead=s.leads[0];expect(lead).toBeDefined();expect(lead.expires-s.tick).toBe(P.starterTTL);expect(P.starterTTL).toBe(1200);});
 it('merges real matching tiers, keeps rank-zero board constraints, persists the package and fulfills only a complete order',()=>{let s=accountFixture();const before=arr(s);s=command(s,{type:'merge',account:800,from:0,to:1,expectedTier:1});expect(s.package.board??initialBoard()).toEqual(initialBoard());s=command(s,{type:'merge',account:800,from:0,to:10,expectedTier:1});expect(s.package.board![0]).toEqual({family:0,tier:1});s.ranks.expansion.scale=2;s=command(s,{type:'merge',account:800,from:0,to:10,expectedTier:1});expect(s.package.board![0]).toBeNull();expect(s.package.board![10]).toEqual({family:0,tier:1});s=command(s,{type:'expand',account:800});expect(arr(s)).toBe(before);s=combine(s);expect(s.package.board!.reduce((n,t)=>n+(t?2**(t.tier-1):0),0)).toBe(8);expect(mergeOrder(0).every(w=>s.package.board!.some(t=>t?.family===w.family&&t.tier===w.tier))).toBe(true);const saved=decodeSave(encodeSave(s));expect(saved.package).toEqual(s.package);s=command(s,{type:'expand',account:800});expect(arr(s)).toBeGreaterThan(before);expect(s.accounts[0].addons).toBe(1);const expanded=arr(s);s=command(s,{type:'expand',account:800});expect(arr(s)).toBe(expanded);});
 it('cannot strand the second order by generating excess of one feature family',()=>{let s=accountFixture();s.accounts[0].addons=1;s=combine(s);for(let n=0;n<10;n++)s=command(s,{type:'supply',account:800,family:0});expect(s.package.supplied).toBe(12);s=combine(s);for(let n=0;n<4;n++)s=command(s,{type:'supply',account:800,family:1});s=combine(s);expect(mergeOrder(1).every(w=>s.package.board!.some(t=>t?.family===w.family&&t.tier===w.tier))).toBe(true);});
 it('recovers an overmerged board once without minting supply, cash, slots or ARR',()=>{let s=accountFixture();s=combine(s);s=command(s,{type:'merge',account:800,from:0,to:1,expectedTier:3});expect(s.package.board).not.toEqual(initialBoard());const cash=s.cash,before=arr(s);s=command(s,{type:'recover-package',account:800});expect(s.package).toMatchObject({id:800,supplied:8,recovered:true,board:initialBoard()});expect(s.cash).toBe(cash);expect(arr(s)).toBe(before);const recovered=structuredClone(s.package);s=command(s,{type:'recover-package',account:800});expect(s.package).toEqual(recovered);expect(decodeSave(encodeSave(s)).package).toEqual(recovered);});
 it('serves a valid package exactly once, books addon ARR, raises service load and delays cash collection',()=>{let s=rebaseCompany(accountFixture(901));s=combine(s);const beforeArr=arr(s),beforeCost=monthlyCost(s),beforeCash=s.cash;s=command(s,{type:'expand',account:800});const added=Math.round(4000*P.addon_price_fraction)*12;expect(arr(s)-beforeArr).toBe(added);expect(s.accounts[0].addons).toBe(1);expect(monthlyCost(s)-beforeCost).toBe(Math.round(P.monthlyService[0]*P.addon_service_cost_fraction));expect(s.cash).toBe(beforeCash-P.functions.expansion.attempt_cost_cents);expect(s.expansionResolution).toMatchObject({accountId:800,addonSlot:1,arrDelta:added,serviceCostDelta:Math.round(P.monthlyService[0]*P.addon_service_cost_fraction),collectionDue:1860,outcome:'served'});expect(s.invoices).toHaveLength(0);const served=arr(s);s=command(s,{type:'expand',account:800});expect(arr(s)).toBe(served);expect(s.actionResults.at(-1)?.reason).toBe('stale-job');expect(replayCompany(s)).toEqual(s);});
 it('rejects stale customers and hands a persisted board safely between founder and agent',()=>{let stale=accountFixture(902);stale=command(stale,{type:'merge',account:800,from:0,to:2,expectedTier:1});stale.accounts[0].health=20;const before=arr(stale);stale=command(stale,{type:'expand',account:800});expect(arr(stale)).toBe(before);expect(stale.actionResults.at(-1)?.reason).toBe('stale-job');expect(stale.package.id).toBe(800);
  let manual=accountFixture(903);manual=command(manual,{type:'merge',account:800,from:0,to:2,expectedTier:1});manual=command(manual,{type:'cancel-job',job:'expansion:800'});manual.ranks.expansion.automate=4;manual.deployed.expansion=0;manual.cash=1_000_000;manual.focus='demand';manual=advance(manual,300);expect(manual.accounts[0].addons).toBe(0); // cancelled work stays closed
  let handoff=accountFixture(904);handoff.ranks.expansion.automate=4;handoff.deployed.expansion=0;handoff.cash=1_000_000;handoff.focus='demand';handoff=rebaseCompany(handoff);handoff=advance(handoff,50);expect(handoff.jobs.reservations[0]?.owner).toBe('agent:expansion');handoff=command(handoff,{type:'automation',work:'expansion'});expect(handoff.jobs.reservations).toHaveLength(0);handoff.focus='expansion';handoff=rebaseCompany(handoff);handoff=combine(handoff);handoff=command(handoff,{type:'expand',account:800});expect(handoff.accounts[0].addons).toBe(1);expect(replayCompany(handoff)).toEqual(handoff);});
 it('gives all sixteen Expansion ranks stable effects and keeps rank-zero package output deterministic',()=>{for(const axis of ['craft','scale','automate','luck'] as const)for(let rank=1;rank<=4;rank++)expect(skillRank('expansion',axis,rank)).toMatchObject({id:`expansion.${axis}.${rank}`,effectId:`skill:expansion.${axis}.${rank}`});let a=accountFixture(905),b=accountFixture(905);a=combine(a);b=combine(b);a=command(a,{type:'expand',account:800});b=command(b,{type:'expand',account:800});expect(a.expansionResolution).toEqual(b.expansionResolution);expect(a.expansionResolution?.luckDelta).toBe(0);});
 it('squashes a finite real problem without rebooking ARR, rejects stale progress, and survives reload',()=>{let s=rebaseCompany(retentionFixture());const before=arr(s),id=s.accounts[0].problem!.id;s=command(s,{type:'squash-problem',account:800,problem:id,expected:0});expect(s.accounts[0].problem?.workCompleted).toBe(1);const duplicate=command(s,{type:'squash-problem',account:800,problem:id,expected:0});expect(duplicate.accounts[0].problem?.workCompleted).toBe(1);expect(duplicate.actionResults.at(-1)?.reason).toBe('stale-job');s=decodeSave(encodeSave(s));for(let n=1;n<8;n++)s=command(s,{type:'squash-problem',account:800,problem:id,expected:n});expect(s.accounts[0].problem).toBeUndefined();expect(s.accounts[0].threat).toBe(0);expect(s.accounts[0].caredUntil).toBeGreaterThan(s.tick);expect(arr(s)).toBe(before);expect(s.retentionResolution).toMatchObject({outcome:'health-restored',protectedArr:before,concessionArrDelta:0});expect(replayCompany(s)).toEqual(s);});
 it('uses the same finite Retention resolver for manual and agent work, and every Retention rank has an effect record',()=>{let manual=retentionFixture(811);manual.ranks.retention.craft=2;const id=manual.accounts[0].problem!.id;manual=rebaseCompany(manual);manual=command(manual,{type:'squash-problem',account:800,problem:id,expected:0});expect(manual.retentionResolution).toMatchObject({outcome:'progress',workAdded:4,workCompleted:4,workRequired:8});let agent=retentionFixture(811);agent.ranks.retention.craft=2;agent.ranks.retention.automate=4;agent.deployed.retention=0;agent.cash=1_000_000;agent=rebaseCompany(agent);agent=advance(agent,300);expect(agent.retentionResolution?.workAdded).toBe(4);expect(agent.accounts[0].problem).toBeUndefined();for(const axis of ['craft','scale','automate','luck'] as const)for(let rank=1;rank<=4;rank++)expect(skillRank('retention',axis,rank)).toMatchObject({id:`retention.${axis}.${rank}`,effectId:`skill:retention.${axis}.${rank}`});expect(replayCompany(agent)).toEqual(agent);});
 it('cancels a founder-held problem without a phantom rescue and batches distinct account problems through one agent',()=>{let cancelled=rebaseCompany(retentionFixture(812));const id=cancelled.accounts[0].problem!.id;cancelled=command(cancelled,{type:'squash-problem',account:800,problem:id,expected:0});cancelled=command(cancelled,{type:'cancel-job',job:'retention:800'});cancelled.ranks.retention.automate=4;cancelled.deployed.retention=0;cancelled.cash=1_000_000;cancelled=advance(cancelled,40);expect(cancelled.accounts[0].problem?.workCompleted).toBe(0);const stale=command(cancelled,{type:'squash-problem',account:800,problem:id,expected:0});expect(stale.actionResults.at(-1)?.reason).toBe('cancelled-job');expect(arr(cancelled)).toBe(48000);
  let batch=retentionFixture(813);batch.accounts.push({id:802,origin:802,segment:1,count:1,price:9000,basePrice:9000,fit:.8,health:76,defects:0,born:0,caredUntil:0,addons:0,threat:batch.tick+90,problem:{id:803,kind:'handoff',label:'Approval handoff stalled',detail:'A second real account needs help.',openedAt:batch.tick,deadline:batch.tick+90,severity:1,workRequired:4,workCompleted:0,exposedArr:108000},earned:0,remainder:0,active:true});batch.ranks.retention={craft:4,scale:1,automate:4,luck:0};batch.deployed.retention=0;batch.cash=1_000_000;const before=arr(batch);batch=rebaseCompany(batch);batch=advance(batch,360);expect(batch.accounts.every(a=>!a.problem)).toBe(true);expect(arr(batch)).toBe(before);expect(batch.completed.retention).toBe(2);expect(replayCompany(batch)).toEqual(batch);});
 it('commits the visible timing contract deterministically at Luck 0 and rejects malformed timing',()=>{let s=start();s.focus='monetisation';s.trials=[{id:99,segment:0,count:1,fit:1,expires:1000}];const target=priceTarget(s),fair=pricingQuote(s,'fair',false,target.center),premium=pricingQuote(s,'premium',false,target.center),miss=pricingQuote(s,'fair',false,target.center<.5?1:0);expect(fair.valid).toBe(true);expect(premium.valid).toBe(true);expect(miss.valid).toBe(false);const before=s.cash;const invalid=command(s,{type:'price',job:99,plan:'fair',timing:2});expect(invalid.cash).toBe(before);expect(invalid.trials.length).toBe(1);s=command(s,{type:'price',job:99,plan:'fair',timing:target.center});expect(s.trials.length).toBe(0);expect(s.accounts).toHaveLength(1);expect(arr(s)).toBe(fair.baseArr);expect(s.cash).toBe(before);expect(s.actionResults.at(-1)?.pricing).toMatchObject({outcome:'signed',customers:1,arrDelta:fair.baseArr,luckDelta:0});expect(s.actions.at(-1)?.command).toMatchObject({type:'price',timing:target.center});});
 it('uses a replayable named Luck pricing stream and never changes cash at contract commitment',()=>{const make=(seed:number)=>{let s=start(seed);s.focus='monetisation';s.ranks.monetisation.luck=2;s.risky.monetisation=true;s.trials=[{id:77,segment:1,count:1,fit:.9,expires:1000}];s=rebaseCompany(s);const target=priceTarget(s);const cash=s.cash;s=command(s,{type:'price',job:77,plan:'fair',timing:target.center});return {s,cash};};const first=make(701),again=make(701);expect(first.s).toEqual(again.s);const result=first.s.actionResults.at(-1)?.pricing;expect(result).toBeDefined();expect(result?.luckRank).toBe(2);expect(result?.contractPrice).toBe(Math.round(result!.basePrice*(1+result!.luckDelta*.04)));expect(first.s.cash).toBe(first.cash);expect(first.s.accounts[0].price*12).toBe(result?.arrDelta);expect(replayCompany(first.s)).toEqual(first.s);});
 it('keeps manual room actions responsive while preserving semantic queue guards',()=>{let s=start();s.focus='demand';for(let i=0;i<3;i++)s=command(s,{type:'demand',pursue:true,signal:s.signal});expect(s.attempts.demand).toBe(3);expect(s.tick).toBe(0);const leads=s.leads.length;s=command(s,{type:'price',job:999,plan:'fair',timing:.5});expect(s.leads.length).toBe(leads);});
 it('gives different cohorts stable seeded Monetisation windows',()=>{const s=start(91);s.trials=[{id:10,segment:0,count:1,fit:.8,expires:1000}];const first=priceTarget(s);expect(priceTarget(s)).toEqual(first);s.trials[0]={...s.trials[0],id:11};expect(priceTarget(s).center).not.toBe(first.center);});
 it('keeps the pricing meter bounded and bouncing with no end-to-start jump',()=>{const s=start();let last=priceCursor(s);for(let t=1;t<=96;t++){s.tick=t;const next=priceCursor(s);expect(next).toBeGreaterThanOrEqual(0);expect(next).toBeLessThanOrEqual(1);expect(Math.abs(next-last)).toBeLessThan(.09);last=next;}});
 it('offers relevant typed rewards without charging a second upgrade economy',()=>{let s=start();s.quarter=7;s.tick=12599;s.cash=1000000;s=advance(s,1);const r=s.reports.at(-1)!;expect(r.choices.length).toBeGreaterThan(0);expect(r.choices.length).toBeLessThanOrEqual(P.rewardDraftSize);expect(r.choices.some(id=>id.startsWith('relic:'))).toBe(true);expect(r.choices).not.toContain('consumable:customer-firebreak');const id=r.choices[0],before=s.cash;s=command(s,{type:'draft',quarter:7,id});expect(s.reports.at(-1)?.chosen).toBe(id);expect(s.cash).toBe(before);expect(s.inventory.relics.includes(id)||s.inventory.consumables[id]===1).toBe(true);const installed=s.inventory;s=command(s,{type:'draft',quarter:7,id});expect(s.inventory).toEqual(installed);validateCompany(s);});
 it('allows passing a quarter without cash cost, and rejects subsequently selecting it',()=>{let s=advance(start(),1800);const cash=s.cash;s=command(s,{type:'draft-skip',quarter:1});s=command(s,{type:'draft',quarter:1,id:s.reports[0].choices[0]});expect(s.cash).toBe(cash);expect(s.reports[0].chosen).toBe('passed');expect(s.upgrades).toHaveLength(0);expect(replayCompany(s)).toEqual(s);});
 it('migrates previous saves without resetting company finances and replays from the migration checkpoint',()=>{const old=advance(start(),50);const migrated=decodeSave(legacySave(old,'founder-candidate.2'));expect(migrated.cash).toBe(old.cash);expect(migrated.tick).toBe(old.tick);expect(migrated.migratedActions).toEqual(old.actions.map(({tick,command})=>({tick,command})));const next=advance(command(migrated,{type:'focus',work:'operations'}),20);expect(replayCompany(next)).toEqual(next);});
});
