import type { ActionId, AgentId, CohortId, CustomerId, EntityId } from './ids';
import type { FunctionId } from './actions';
import type { AnnualDollars, Cents, PressureUnits, Tick } from './units';

export const DOMAIN_EVENT_TYPES = [
  'ACTION_ACCEPTED', 'ACTION_REJECTED', 'RUN_PHASE_CHANGED', 'FOUNDER_ATTENTION_CHANGED',
  'MARKETING_OPPORTUNITY_RESOLVED', 'DEMAND_COHORT_CREATED', 'DEMAND_COHORT_EXPIRED',
  'PRODUCT_COMPONENT_ACCEPTED', 'PRODUCT_COMPONENT_REJECTED', 'PRODUCT_RECIPE_TESTED', 'PRODUCT_RECIPE_SHIPPED',
  'ACTIVATED_COHORT_CREATED', 'PRICING_MODEL_CHANGED', 'PRICING_COMMITTED', 'CUSTOMER_CONVERTED',
  'RETENTION_PRIORITY_CHANGED', 'RETENTION_THREAT_RESOLVED', 'CHURN_PREVENTED', 'CUSTOMER_CHURNED',
  'EXPANSION_ITEM_MERGED', 'EXPANSION_PACKAGE_COMMITTED', 'EXPANSION_BOOKED',
  'QUEUE_CHANGED', 'ARR_CHANGED', 'CASH_CHANGED', 'COLLECTIONS_POSTED', 'BURN_CHANGED',
  'AGENT_INSTALLED', 'AGENT_ASSIGNED', 'AGENT_WORKED', 'AGENT_FAILED', 'AGENT_LINE_RESET',
  'COMPLEXITY_CHANGED', 'OPS_CAPACITY_CHANGED', 'STRAIN_BAND_CHANGED', 'ROT_CHANGED',
  'INCIDENT_CREATED', 'OPERATIONS_EVIDENCE_REVEALED', 'OPERATIONS_OBLIGATION_RESOLVED', 'OPTIMIZER_RESOLVED',
  'FINANCE_OFFER_CREATED', 'FINANCE_OFFER_RESOLVED', 'DEBT_DRAWN', 'DEBT_OBLIGATION_DUE',
  'DEBT_PAYMENT_POSTED', 'DEBT_INTEREST_CAPITALIZED', 'OWNERSHIP_CHANGED', 'GROWTH_ARREARS_CHANGED',
  'SKILL_RANK_PURCHASED', 'RELIC_ACQUIRED', 'STRATEGY_ACTIVATED', 'EFFECT_APPLIED',
  'QUARTER_CLOSED', 'GROWTH_MANDATE_MET', 'GROWTH_MANDATE_MISSED', 'VALUATION_RERATED',
  'FAILURE_CANDIDATE_CREATED', 'RUN_FAILED', 'UNICORN_REACHED', 'RUN_CONTINUED', 'STATE_CHECKPOINTED',
] as const;

export type DomainEventType = (typeof DOMAIN_EVENT_TYPES)[number];
export type LedgerCategory = 'ARR' | 'CASH' | 'DEBT' | 'EQUITY' | 'COHORT' | 'QUEUE' | 'PRESSURE' | 'PROGRESSION' | 'RUN';
export type ReasonCode =
  | 'PLAYER_ACTION' | 'MARKETING_QUALIFIED' | 'MARKETING_LOW_QUALITY' | 'PRODUCT_VERIFIED' | 'PRODUCT_EARLY_SHIP'
  | 'MONETIZATION_PRICE' | 'CUSTOMER_COLLECTION' | 'RETENTION_SAVE' | 'CUSTOMER_CHURN' | 'EXPANSION_FIT'
  | 'AGENT_STRUCTURE' | 'AUTONOMOUS_OPERATION' | 'OPERATIONS_RECOVERY' | 'SKILL_EFFECT' | 'RELIC_EFFECT'
  | 'STRATEGY_EFFECT' | 'FINANCE_TRANSACTION' | 'DEBT_SERVICE' | 'QUARTER_CLOSE' | 'MANDATE_FAILURE'
  | 'BANKRUPTCY' | 'AUTOMATION_COLLAPSE' | 'CONTEXT_CORRUPTION' | 'INVALID_ACTION';

export type CausalDelta = {
  category: LedgerCategory;
  reason: ReasonCode;
  amount: number;
  unit: 'ANNUAL_DOLLARS' | 'CENTS' | 'BASIS_POINTS' | 'WORK_UNITS' | 'PRESSURE_UNITS' | 'COUNT';
  sourceIds: EntityId[];
  originatingActionId?: ActionId;
};

export type DomainEvent<T extends DomainEventType = DomainEventType> = {
  eventVersion: 1;
  eventId: EntityId;
  sequence: number;
  atTick: Tick;
  type: T;
  payload: Record<string, unknown> & {
    actionId?: ActionId;
    functionId?: FunctionId;
    cohortId?: CohortId;
    customerId?: CustomerId;
    agentId?: AgentId;
    annualDollars?: AnnualDollars;
    cents?: Cents;
    pressureUnits?: PressureUnits;
  };
  delta?: CausalDelta;
};
