import type { FunctionId } from '../../schema/actions';
import type { CalibrationValue } from '../../schema/balance';
import type { ContentPack, GameContent, SkillRankContent } from '../../schema/content';
import { asContentId } from '../../schema/ids';
import { annualDollars, basisPoints, cents, ppm, pressureUnits, tick, workUnits } from '../../schema/units';

const cal = <T>(value: T, unit: string, dependencyId: `B${string}`, rationale: string): CalibrationValue<T> => ({ value, unit, status: 'CALIBRATION', dependencyId, rationale });
const base = (id: string, name: string, description: string, tags: string[], assetKey = `reserved/${id}`) => ({
  schemaVersion: 1 as const, id: asContentId(id), name, description, tags, assetKey, provenance: 'CALIBRATION' as const,
});

const signals: GameContent[] = [
  { ...base('signal.support-tabs', 'Support teams want fewer tabs', 'A durable operations painkiller with clear purchase intent.', ['support', 'durable']), kind: 'MARKETING_SIGNAL', segment: 'SUPPORT_OPS', revealed: { audienceFit: 'Excellent', purchaseIntent: 'High', trendVelocity: 'Steady', saturation: 'Low' }, quality: 'EXCEPTIONAL', requirements: [asContentId('recipe.workflow-hub')], demandUnits: cal(workUnits(3_000), 'milli-work', 'B03', 'Golden qualified demand.'), aggressiveDemandUnits: cal(workUnits(5_000), 'milli-work', 'B03', 'Golden aggressive demand.'), pursueCostCents: cal(cents(26_000), 'cents', 'B03', 'Golden acquisition cost.'), aggressiveCostCents: cal(cents(72_000), 'cents', 'B03', 'Golden acquisition cost.') },
  { ...base('signal.finance-sheet', 'AI spreadsheets are having a week', 'Loud attention with incomplete buying intent.', ['finance', 'volatile']), kind: 'MARKETING_SIGNAL', segment: 'FINANCE_OPS', revealed: { audienceFit: 'Strong', purchaseIntent: 'Partial', trendVelocity: 'Fast', saturation: 'High' }, quality: 'QUALIFIED', requirements: [asContentId('recipe.ai-search')], demandUnits: cal(workUnits(2_000), 'milli-work', 'B03', 'Golden qualified demand.'), aggressiveDemandUnits: cal(workUnits(4_000), 'milli-work', 'B03', 'Golden aggressive demand.'), pursueCostCents: cal(cents(42_000), 'cents', 'B03', 'Golden acquisition cost.'), aggressiveCostCents: cal(cents(120_000), 'cents', 'B03', 'Golden acquisition cost.') },
  { ...base('signal.agent-studio', 'Everyone is suddenly an agent studio', 'Huge attention, low intent, punishing saturation.', ['creator', 'low-quality']), kind: 'MARKETING_SIGNAL', segment: 'CREATOR_TOOLS', revealed: { audienceFit: 'Medium', purchaseIntent: 'Low', trendVelocity: 'Viral', saturation: 'Severe' }, quality: 'LOW', requirements: [asContentId('recipe.agent-studio')], demandUnits: cal(workUnits(2_000), 'milli-work', 'B03', 'Golden low-quality demand.'), aggressiveDemandUnits: cal(workUnits(6_000), 'milli-work', 'B03', 'Golden aggressive demand.'), pursueCostCents: cal(cents(89_000), 'cents', 'B03', 'Golden acquisition cost.'), aggressiveCostCents: cal(cents(180_000), 'cents', 'B03', 'Golden acquisition cost.') },
];

const recipes: GameContent[] = [
  { ...base('recipe.workflow-hub', 'Support Workflow Hub', 'Route support context into one reliable workspace.', ['product', 'support']), kind: 'PRODUCT_RECIPE', componentIds: ['component.inbox', 'component.routing', 'component.context'].map(asContentId), slotIds: ['intake', 'logic', 'memory'], activationQualityPpm: cal(ppm(900_000), 'ppm', 'B03', 'Verified golden recipe quality.'), earlyShipRiskPpm: cal(ppm(260_000), 'ppm', 'B03', 'Early ship risk calibration.') },
  { ...base('recipe.ai-search', 'AI Search', 'Grounded retrieval with evaluation before deploy.', ['product', 'finance']), kind: 'PRODUCT_RECIPE', componentIds: ['component.data', 'component.retrieval', 'component.eval'].map(asContentId), slotIds: ['source', 'engine', 'proof'], activationQualityPpm: cal(ppm(820_000), 'ppm', 'B03', 'Verified golden recipe quality.'), earlyShipRiskPpm: cal(ppm(340_000), 'ppm', 'B03', 'Early ship risk calibration.') },
  { ...base('recipe.agent-studio', 'Agent Studio', 'Composable agent workflow with explicit permissions.', ['product', 'creator']), kind: 'PRODUCT_RECIPE', componentIds: ['component.tools', 'component.permissions', 'component.trace'].map(asContentId), slotIds: ['tools', 'guardrail', 'trace'], activationQualityPpm: cal(ppm(720_000), 'ppm', 'B03', 'Verified golden recipe quality.'), earlyShipRiskPpm: cal(ppm(470_000), 'ppm', 'B03', 'Early ship risk calibration.') },
];

const customers: GameContent[] = [
  ['customer.support-scaleup', 'Support Scaleup', 'SUPPORT_OPS', 18_000, 'PER_SEAT'],
  ['customer.finance-team', 'Finance Team', 'FINANCE_OPS', 24_000, 'FLAT'],
  ['customer.creator-studio', 'Creator Studio', 'CREATOR_TOOLS', 12_000, 'USAGE'],
  ['customer.enterprise-ops', 'Enterprise Operations', 'ENTERPRISE', 45_000, 'PER_SEAT'],
].map(([id, name, segment, arr, model]) => ({ ...base(String(id), String(name), 'A deterministic golden customer archetype.', ['customer', String(segment).toLowerCase()]), kind: 'CUSTOMER_ARCHETYPE' as const, segment: String(segment), pricingModel: model as 'FLAT' | 'PER_SEAT' | 'USAGE', baseArr: cal(annualDollars(Number(arr)), 'annual dollars', 'B03', 'Golden customer ARR.'), perfectBandStartPpm: cal(ppm(440_000), 'ppm cycle', 'B03', 'Golden timing band.'), perfectBandEndPpm: cal(ppm(600_000), 'ppm cycle', 'B03', 'Golden timing band.'), expansionPotentialPpm: cal(ppm(300_000), 'ppm', 'B06', 'Golden expansion capacity.') }));

const functions: FunctionId[] = ['MARKETING', 'PRODUCT', 'MONETIZATION', 'RETENTION', 'EXPANSION', 'OPERATIONS', 'FINANCE'];
const branches = ['CRAFT', 'SCALE', 'AUTONOMY', 'VARIANCE'] as const;
const skills: SkillRankContent[] = functions.flatMap((functionId) => branches.map((branch, index) => {
  const slug = `${functionId.toLowerCase()}.${branch.toLowerCase()}.1`;
  return { ...base(`skill.${slug}`, `${functionId[0]}${functionId.slice(1).toLowerCase()} ${branch[0]}${branch.slice(1).toLowerCase()} I`, `A first ${branch.toLowerCase()} rank for ${functionId.toLowerCase()}.`, ['skill', functionId.toLowerCase(), branch.toLowerCase()]), kind: 'SKILL_RANK', functionId, branch, subbranch: 'FOUNDATION', tier: 1, prerequisiteIds: [], costCents: cal(cents(350_000 + index * 50_000), 'cents', 'B07', 'Golden first-rank cost.'), eligibility: [{ type: 'ALWAYS' }], effects: [{ id: asContentId(`effect.${slug}`), scope: { type: 'FUNCTION', functionId }, duration: { type: 'PERMANENT' }, stacking: 'ADD', precedence: 100, reversible: false, operation: branch === 'CRAFT' ? { type: 'ADD_CAPACITY', amount: workUnits(250) } : branch === 'SCALE' ? { type: 'MODIFY_QUEUE_LIMIT', amount: 1 } : branch === 'AUTONOMY' ? { type: 'ADD_COMPLEXITY', amount: pressureUnits(900) } : { type: 'MODIFY_RISK_DISTRIBUTION', amountPpm: ppm(40_000) } }] };
}));

const supporting: GameContent[] = [
  { ...base('history.fresh-founder', 'Fresh Founder', 'Standardized baseline with no inferred biography.', ['history', 'baseline']), kind: 'FOUNDER_HISTORY', effects: [] },
  { ...base('history.ops-apprentice', 'Systems Apprentice', 'Starts closer to Operations and away from hype.', ['history', 'operations']), kind: 'FOUNDER_HISTORY', weightedFunction: 'OPERATIONS', effects: [{ id: asContentId('effect.history.ops'), scope: { type: 'COMPANY' }, duration: { type: 'PERMANENT' }, stacking: 'ADD', precedence: 50, reversible: false, operation: { type: 'ADD_OPS_CAPACITY', amount: pressureUnits(1_000) } }] },
  { ...base('agent.worker.marketing', 'Signal Worker', 'Processes the same Marketing opportunities as the founder.', ['agent', 'marketing']), kind: 'AGENT_TIER', tier: 1, throughput: cal(workUnits(350), 'milli-work/tick', 'B12', 'Agent calibration.'), reliabilityPpm: cal(ppm(860_000), 'ppm', 'B12', 'Agent calibration.'), recurringCostCents: cal(cents(180_000), 'cents/quarter', 'B12', 'Agent calibration.'), complexity: cal(pressureUnits(1_400), 'milli-complexity', 'B08', 'Agent structure cost.') },
  { ...base('agent.operator.product', 'Product Operator', 'Assembles known recipes and escalates exceptions.', ['agent', 'product']), kind: 'AGENT_TIER', tier: 2, throughput: cal(workUnits(520), 'milli-work/tick', 'B12', 'Agent calibration.'), reliabilityPpm: cal(ppm(920_000), 'ppm', 'B12', 'Agent calibration.'), recurringCostCents: cal(cents(320_000), 'cents/quarter', 'B12', 'Agent calibration.'), complexity: cal(pressureUnits(2_100), 'milli-complexity', 'B08', 'Agent structure cost.') },
  { ...base('threat.workflow-broken', 'Broken Workflow', 'Product quality is damaging a customer workflow.', ['retention']), kind: 'RETENTION_THREAT', severity: 3, workRequired: cal(workUnits(2_000), 'milli-work', 'B05', 'Threat calibration.'), timeToChurn: cal(tick(80), 'ticks', 'B05', 'Threat calibration.') },
  { ...base('ops.retry-storm', 'Agent Retry Storm', 'Autonomous work is repeating without convergence.', ['operations']), kind: 'OPERATIONS_OBLIGATION', evidenceCells: ['trace', 'policy', 'handoff'], resolutionIds: [asContentId('resolution.cap-retries'), asContentId('resolution.reset-line')], rotPerTick: cal(pressureUnits(8), 'milli-rot/tick', 'B11', 'Operations calibration.') },
  { ...base('finance.runway-note', 'Runway Note', 'Short-term debt that preserves ownership and creates interest pressure.', ['finance', 'debt']), kind: 'FINANCE_INSTRUMENT', principalCents: cal(cents(2_500_000), 'cents', 'B15', 'Debt calibration.'), aprBps: cal(basisPoints(1_600), 'basis points', 'B15', 'Debt calibration.'), termTicks: cal(tick(720), 'ticks', 'B15', 'Debt calibration.') },
  { ...base('strategy.product-led', 'Product-Led', 'Verified Product success creates organic Demand.', ['strategy', 'product']), kind: 'STRATEGY', durationQuarters: 2, eligibility: [{ type: 'ALWAYS' }], effects: [{ id: asContentId('effect.strategy.product-led'), scope: { type: 'COMPANY' }, duration: { type: 'QUARTERS', quarters: 2 }, stacking: 'UNIQUE', precedence: 100, reversible: true, operation: { type: 'ADD_ELIGIBILITY_TAG', tag: 'ORGANIC_DEMAND' } }] },
  { ...base('strategy.reliability-quarter', 'Reliability Quarter', 'Lower growth intensity in exchange for Rot recovery.', ['strategy', 'operations']), kind: 'STRATEGY', durationQuarters: 1, eligibility: [{ type: 'ALWAYS' }], effects: [{ id: asContentId('effect.strategy.reliability'), scope: { type: 'COMPANY' }, duration: { type: 'QUARTERS', quarters: 1 }, stacking: 'ADD', precedence: 100, reversible: true, operation: { type: 'MODIFY_ROT_RATE', multiplierPpm: ppm(600_000) } }] },
  { ...base('relic.actually-read-diff', 'Actually Read the Diff', 'Manual Product is slower, but verified outcomes are safer.', ['relic', 'product']), kind: 'RELIC', rarity: 'RARE', eligibility: [{ type: 'FUNCTION_RANK', functionId: 'PRODUCT', branch: 'CRAFT', rank: 1 }], effects: [{ id: asContentId('effect.relic.read-diff'), scope: { type: 'FUNCTION', functionId: 'PRODUCT' }, duration: { type: 'PERMANENT' }, stacking: 'ADD', precedence: 200, reversible: false, operation: { type: 'MODIFY_RELIABILITY', amountPpm: ppm(70_000) } }] },
  { ...base('relic.one-more-agent', 'One More Agent', 'A free worker with a very real coordination bill.', ['relic', 'agent']), kind: 'RELIC', rarity: 'COMMON', eligibility: [{ type: 'MIN_AGENTS', count: 1 }], effects: [{ id: asContentId('effect.relic.one-more-agent'), scope: { type: 'COMPANY' }, duration: { type: 'PERMANENT' }, stacking: 'ADD', precedence: 200, reversible: false, operation: { type: 'ADD_COMPLEXITY', amount: pressureUnits(1_500) } }] },
];

export const V2_GOLDEN_CONTENT: ContentPack = { schemaVersion: 1, version: 'v2-golden.1', cultureVersion: 'opu-culture.1', entries: [...signals, ...recipes, ...customers, ...skills, ...supporting] };

export const contentById = new Map(V2_GOLDEN_CONTENT.entries.map((entry) => [entry.id, entry]));
